$outPath = 'c:\Users\SohaibAli\Videos\Development\AnalystDevelopmentFrontend\src\page-components\KnowledgeBasePage.tsx'  
Set-Content -Path $outPath -Value "'use client';" -Encoding UTF8  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "import React, { useState, useEffect, useCallback, useMemo } from 'react';"  
Add-Content -Path $outPath -Value "import {"  
Add-Content -Path $outPath -Value "  Database,"  
Add-Content -Path $outPath -Value "  FileText,"  
Add-Content -Path $outPath -Value "  Search,"  
Add-Content -Path $outPath -Value "  Upload,"  
Add-Content -Path $outPath -Value "  FolderOpen,"  
Add-Content -Path $outPath -Value "  HardDrive,"  
Add-Content -Path $outPath -Value "  Loader2,"  
Add-Content -Path $outPath -Value "  AlertCircle,"  
Add-Content -Path $outPath -Value "  RefreshCw,"  
Add-Content -Path $outPath -Value "  Bookmark,"  
Add-Content -Path $outPath -Value "  BookmarkCheck,"  
Add-Content -Path $outPath -Value "  Sparkles,"  
Add-Content -Path $outPath -Value "  MessageSquarePlus,"  
Add-Content -Path $outPath -Value "  Clock,"  
Add-Content -Path $outPath -Value "  TrendingUp,"  
Add-Content -Path $outPath -Value "  BookOpen,"  
Add-Content -Path $outPath -Value "  X,"  
Add-Content -Path $outPath -Value "  CheckCircle2,"  
Add-Content -Path $outPath -Value "  AlertTriangle,"  
Add-Content -Path $outPath -Value "} from 'lucide-react';" 
Add-Content -Path $outPath -Value "import kbApi from '@/lib/kbApi';"  
Add-Content -Path $outPath -Value "import type { KBDocument, KBStats } from '@/types/kb';"  
Add-Content -Path $outPath -Value "import { useTheme } from '@/contexts/ThemeContext';"  
Add-Content -Path $outPath -Value "import { useResponsive } from '@/hooks/useResponsive';"  
Add-Content -Path $outPath -Value "import FeedbackModal from '@/components/FeedbackModal';"  
Add-Content -Path $outPath -Value "import KBFileViewerModal from '@/components/knowledge/KBFileViewerModal';" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "type TabId = 'discover' ^| 'documents' ^| 'upload';"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "const TABS: { id: TabId; label: string; icon: React.ElementType }[] = ["  
Add-Content -Path $outPath -Value "  { id: 'discover', label: 'DISCOVER', icon: Sparkles },"  
Add-Content -Path $outPath -Value "  { id: 'documents', label: 'DOCUMENTS', icon: FileText },"  
Add-Content -Path $outPath -Value "  { id: 'upload', label: 'UPLOAD', icon: Upload },"  
Add-Content -Path $outPath -Value "];" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function formatFileSize(bytes: number ^| null ^| undefined) {"  
Add-Content -Path $outPath -Value "  const n = Number(bytes ?? 0);"  
Add-Content -Path $outPath -Value "  if (n ^< 1024) return n + ' B';"  
Add-Content -Path $outPath -Value "  if (n ^< 1024 * 1024) return (n / 1024).toFixed(1) + ' KB';"  
Add-Content -Path $outPath -Value "  return (n / (1024 * 1024)).toFixed(2) + ' MB';"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function getExt(filename: string) {"  
Add-Content -Path $outPath -Value "  return filename.split('.').pop()?.toLowerCase() ^|^| '';"  
Add-Content -Path $outPath -Value "}"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function getFileColor(filename: string): string {"  
Add-Content -Path $outPath -Value "  const ext = getExt(filename);"  
Add-Content -Path $outPath -Value "  switch (ext) {"  
Add-Content -Path $outPath -Value "    case 'pdf': return '#ef4444';"  
Add-Content -Path $outPath -Value "    case 'doc': case 'docx': return '#3b82f6';"  
Add-Content -Path $outPath -Value "    case 'txt': case 'md': return '#22c55e';"  
Add-Content -Path $outPath -Value "    case 'csv': case 'xlsx': case 'xls': return '#22c55e';"  
Add-Content -Path $outPath -Value "    case 'json': case 'xml': case 'html': return '#f59e0b';"  
Add-Content -Path $outPath -Value "    default: return '#9ca3af';"  
Add-Content -Path $outPath -Value "  }"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "const catColors: Record^<string, { bg: string; text: string }^> = {"  
Add-Content -Path $outPath -Value "  afl: { bg: 'rgba(254,192,15,0.12)', text: 'var(--accent)' },"  
Add-Content -Path $outPath -Value "  strategy: { bg: 'rgba(34,197,94,0.12)', text: '#22c55e' },"  
Add-Content -Path $outPath -Value "  indicator: { bg: 'rgba(99,102,241,0.12)', text: '#818cf8' },"  
Add-Content -Path $outPath -Value "  documentation: { bg: 'rgba(59,130,246,0.12)', text: '#3b82f6' },"  
Add-Content -Path $outPath -Value "  general: { bg: 'rgba(156,163,175,0.12)', text: '#9ca3af' },"  
Add-Content -Path $outPath -Value "};" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "interface UploadItem {"  
Add-Content -Path $outPath -Value "  file: File;"  
Add-Content -Path $outPath -Value "  status: 'pending' ^| 'uploading' ^| 'processing' ^| 'ready' ^| 'error';"  
Add-Content -Path $outPath -Value "  documentId?: string;"  
Add-Content -Path $outPath -Value "  chunkCount?: number;"  
Add-Content -Path $outPath -Value "  error?: string;"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "export function KnowledgeBasePage() {"  
Add-Content -Path $outPath -Value "  const { resolvedTheme } = useTheme();"  
Add-Content -Path $outPath -Value "  const { isMobile, isTablet } = useResponsive();"  
Add-Content -Path $outPath -Value "  const isDark = resolvedTheme === 'dark';"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const colors = useMemo("  
Add-Content -Path $outPath -Value "    () =^> ({"  
Add-Content -Path $outPath -Value "      background: 'var(--bg)',"  
Add-Content -Path $outPath -Value "      cardBg: 'var(--bg-card)',"  
Add-Content -Path $outPath -Value "      inputBg: 'var(--bg-raised)',"  
Add-Content -Path $outPath -Value "      border: 'var(--border)',"  
Add-Content -Path $outPath -Value "      text: 'var(--text)',"  
Add-Content -Path $outPath -Value "      textMuted: 'var(--text-muted)',"  
Add-Content -Path $outPath -Value "      hoverBg: 'var(--bg-card-hover)',"  
Add-Content -Path $outPath -Value "      accent: 'var(--accent)',"  
Add-Content -Path $outPath -Value "      shadow: 'var(--shadow-card)',"  
Add-Content -Path $outPath -Value "    }),"  
Add-Content -Path $outPath -Value "    [],"  
Add-Content -Path $outPath -Value "  );" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const [documents, setDocuments] = useState^<KBDocument[]^>([]);"  
Add-Content -Path $outPath -Value "  const [stats, setStats] = useState^<KBStats ^| null^>(null);"  
Add-Content -Path $outPath -Value "  const [loading, setLoading] = useState(true);"  
Add-Content -Path $outPath -Value "  const [error, setError] = useState('');"  
Add-Content -Path $outPath -Value "  const [activeTab, setActiveTab] = useState^<TabId^>('discover');"  
Add-Content -Path $outPath -Value "  const [activeCategory, setActiveCategory] = useState('all');"  
Add-Content -Path $outPath -Value "  const [searchQuery, setSearchQuery] = useState('');"  
Add-Content -Path $outPath -Value "  const [viewerDoc, setViewerDoc] = useState^<KBDocument ^| null^>(null);"  
Add-Content -Path $outPath -Value "  const [bookmarkedIds, setBookmarkedIds] = useState^<Set^<string^>^>(new Set());"  
Add-Content -Path $outPath -Value "  const [showFeedback, setShowFeedback] = useState(false);"  
Add-Content -Path $outPath -Value "  const [uploadItems, setUploadItems] = useState^<UploadItem[]^>([]);"  
Add-Content -Path $outPath -Value "  const [dragOver, setDragOver] = useState(false);"  
Add-Content -Path $outPath -Value "  const fileInputRef = React.useRef^<HTMLInputElement^>(null);"  
Add-Content -Path $outPath -Value "  const pollingRefs = React.useRef^<Map^<string, ReturnType^<typeof setInterval^>^>^>(new Map());" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const loadData = useCallback(async () =^> {"  
Add-Content -Path $outPath -Value "    setLoading(true);"  
Add-Content -Path $outPath -Value "    setError('');"  
Add-Content -Path $outPath -Value "    try {"  
Add-Content -Path $outPath -Value "      const [filesRes, statsRes] = await Promise.all(["  
Add-Content -Path $outPath -Value "        kbApi.listFiles({ limit: 200 }),"  
Add-Content -Path $outPath -Value "        kbApi.getStats(),"  
Add-Content -Path $outPath -Value "      ]);"  
Add-Content -Path $outPath -Value "      setDocuments(filesRes.files);"  
Add-Content -Path $outPath -Value "      setStats(statsRes);"  
Add-Content -Path $outPath -Value "    } catch (err) {"  
Add-Content -Path $outPath -Value "      const msg = err instanceof Error ? err.message : 'Failed to load data';"  
Add-Content -Path $outPath -Value "      setError(msg);"  
Add-Content -Path $outPath -Value "    } finally {"  
Add-Content -Path $outPath -Value "      setLoading(false);"  
Add-Content -Path $outPath -Value "    }"  
Add-Content -Path $outPath -Value "  }, []);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  useEffect(() =^> {"  
Add-Content -Path $outPath -Value "    loadData();"  
Add-Content -Path $outPath -Value "    return () =^> {"  
Add-Content -Path $outPath -Value "      pollingRefs.current.forEach((id) =^> clearInterval(id));"  
Add-Content -Path $outPath -Value "    };"  
Add-Content -Path $outPath -Value "  }, [loadData]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const startPolling = useCallback((documentId: string, itemIndex: number) =^> {"  
Add-Content -Path $outPath -Value "    if (pollingRefs.current.has(documentId)) return;"  
Add-Content -Path $outPath -Value "    const intervalId = setInterval(async () =^> {"  
Add-Content -Path $outPath -Value "      try {"  
Add-Content -Path $outPath -Value "        const status = await kbApi.getStatus(documentId);"  
Add-Content -Path $outPath -Value "        setUploadItems((prev) =^>"  
Add-Content -Path $outPath -Value "          prev.map((item, idx) =^> {"  
Add-Content -Path $outPath -Value "            if (idx !== itemIndex) return item;"  
Add-Content -Path $outPath -Value "            if (status.ready) {"  
Add-Content -Path $outPath -Value "              clearInterval(pollingRefs.current.get(documentId)!);"  
Add-Content -Path $outPath -Value "              pollingRefs.current.delete(documentId);"  
Add-Content -Path $outPath -Value "              loadData();"  
Add-Content -Path $outPath -Value "              return { ...item, status: 'ready', chunkCount: status.chunk_count };"  
Add-Content -Path $outPath -Value "            }"  
Add-Content -Path $outPath -Value "            if (status.status === 'error') {"  
Add-Content -Path $outPath -Value "              clearInterval(pollingRefs.current.get(documentId)!);"  
Add-Content -Path $outPath -Value "              pollingRefs.current.delete(documentId);"  
Add-Content -Path $outPath -Value "              return { ...item, status: 'error', error: status.error ?? 'Processing failed' };"  
Add-Content -Path $outPath -Value "            }"  
Add-Content -Path $outPath -Value "            return { ...item, status: 'processing' };"  
Add-Content -Path $outPath -Value "          }),"  
Add-Content -Path $outPath -Value "        );"  
Add-Content -Path $outPath -Value "      } catch { /* ignore */ }"  
Add-Content -Path $outPath -Value "    }, 2000);"  
Add-Content -Path $outPath -Value "    pollingRefs.current.set(documentId, intervalId);"  
Add-Content -Path $outPath -Value "  }, [loadData]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const handleFiles = useCallback("  
Add-Content -Path $outPath -Value "    async (files: File[]) =^> {"  
Add-Content -Path $outPath -Value "      if (files.length === 0) return;"  
Add-Content -Path $outPath -Value "      setActiveTab('upload');"  
Add-Content -Path $outPath -Value "      const newItems: UploadItem[] = files.map((f) =^> ({ file: f, status: 'pending' }));"  
Add-Content -Path $outPath -Value "      setUploadItems((prev) =^> [...newItems, ...prev]);"  
Add-Content -Path $outPath -Value "      for (let i = 0; i ^< newItems.length; i++) {"  
Add-Content -Path $outPath -Value "        const globalIdx = i;"  
Add-Content -Path $outPath -Value "        setUploadItems((prev) =^>"  
Add-Content -Path $outPath -Value "          prev.map((item, idx) =^> (idx === globalIdx ? { ...item, status: 'uploading' } : item)),"  
Add-Content -Path $outPath -Value "        );"  
Add-Content -Path $outPath -Value "        try {"  
Add-Content -Path $outPath -Value "          const result = await kbApi.upload(newItems[i].file);"  
Add-Content -Path $outPath -Value "          setUploadItems((prev) =^>"  
Add-Content -Path $outPath -Value "            prev.map((item, idx) =^>"  
Add-Content -Path $outPath -Value "              idx === globalIdx"  
Add-Content -Path $outPath -Value "                ? { ...item, status: 'processing', documentId: result.document_id }"  
Add-Content -Path $outPath -Value "                : item,"  
Add-Content -Path $outPath -Value "            ),"  
Add-Content -Path $outPath -Value "          );"  
Add-Content -Path $outPath -Value "          if (result.document_id) {"  
Add-Content -Path $outPath -Value "            startPolling(result.document_id, globalIdx);"  
Add-Content -Path $outPath -Value "          }"  
Add-Content -Path $outPath -Value "        } catch (err) {"  
Add-Content -Path $outPath -Value "          setUploadItems((prev) =^>"  
Add-Content -Path $outPath -Value "            prev.map((item, idx) =^>"  
Add-Content -Path $outPath -Value "              idx === globalIdx"  
Add-Content -Path $outPath -Value "                ? { ...item, status: 'error', error: err instanceof Error ? err.message : 'Upload failed' }"  
Add-Content -Path $outPath -Value "                : item,"  
Add-Content -Path $outPath -Value "            ),"  
Add-Content -Path $outPath -Value "          );"  
Add-Content -Path $outPath -Value "        }"  
Add-Content -Path $outPath -Value "      }"  
Add-Content -Path $outPath -Value "    },"  
Add-Content -Path $outPath -Value "    [startPolling],"  
Add-Content -Path $outPath -Value "  );" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const handleDelete = useCallback(async (id: string) =^> {"  
Add-Content -Path $outPath -Value "    try {"  
Add-Content -Path $outPath -Value "      await kbApi.deleteFile(id);"  
Add-Content -Path $outPath -Value "      setDocuments((prev) =^> prev.filter((d) =^> d.id !== id));"  
Add-Content -Path $outPath -Value "      if (stats) setStats({ ...stats, total_documents: stats.total_documents - 1 });"  
Add-Content -Path $outPath -Value "    } catch (err) {"  
Add-Content -Path $outPath -Value "      setError(err instanceof Error ? err.message : 'Delete failed');"  
Add-Content -Path $outPath -Value "    }"  
Add-Content -Path $outPath -Value "  }, [stats]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const categories = useMemo("  
Add-Content -Path $outPath -Value "    () =^> (stats ? ['all', ...Object.keys(stats.categories)] : ['all']),"  
Add-Content -Path $outPath -Value "    [stats],"  
Add-Content -Path $outPath -Value "  );"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const filteredDocs = useMemo(() =^> {"  
Add-Content -Path $outPath -Value "    let docs = activeCategory === 'all' ? documents : documents.filter((d) =^> d.category === activeCategory);"  
Add-Content -Path $outPath -Value "    if (searchQuery.trim()) {"  
Add-Content -Path $outPath -Value "      const q = searchQuery.toLowerCase();"  
Add-Content -Path $outPath -Value "      docs = docs.filter("  
Add-Content -Path $outPath -Value "        (d) =^>"  
Add-Content -Path $outPath -Value "          d.filename.toLowerCase().includes(q) ^|^|"  
Add-Content -Path $outPath -Value "          (d.title ?? '').toLowerCase().includes(q) ^|^|"  
Add-Content -Path $outPath -Value "          (d.category ?? '').toLowerCase().includes(q),"  
Add-Content -Path $outPath -Value "      );"  
Add-Content -Path $outPath -Value "    }"  
Add-Content -Path $outPath -Value "    return docs;"  
Add-Content -Path $outPath -Value "  }, [documents, activeCategory, searchQuery]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const recentDocs = useMemo("  
Add-Content -Path $outPath -Value "    () =^>"  
Add-Content -Path $outPath -Value "      [...documents]"  
Add-Content -Path $outPath -Value "        .sort((a, b) =^> new Date(b.created_at).getTime() - new Date(a.created_at).getTime())"  
Add-Content -Path $outPath -Value "        .slice(0, 6),"  
Add-Content -Path $outPath -Value "    [documents],"  
Add-Content -Path $outPath -Value "  );"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const bookmarkedDocs = useMemo("  
Add-Content -Path $outPath -Value "    () =^> documents.filter((d) =^> bookmarkedIds.has(d.id)),"  
Add-Content -Path $outPath -Value "    [documents, bookmarkedIds],"  
Add-Content -Path $outPath -Value "  );"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const handleBookmark = useCallback((id: string) =^> {"  
Add-Content -Path $outPath -Value "    setBookmarkedIds((prev) =^> {"  
Add-Content -Path $outPath -Value "      const next = new Set(prev);"  
Add-Content -Path $outPath -Value "      if (next.has(id)) next.delete(id);"  
Add-Content -Path $outPath -Value "      else next.add(id);"  
Add-Content -Path $outPath -Value "      return next;"  
Add-Content -Path $outPath -Value "    });"  
Add-Content -Path $outPath -Value "  }, []);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const dot = isDark ? 'rgba(255,255,255,0.025)' : 'rgba(0,0,0,0.03)';"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  return ("  
Add-Content -Path $outPath -Value "    ^<div"  
Add-Content -Path $outPath -Value "      style={{"  
Add-Content -Path $outPath -Value "        minHeight: '100vh',"  
Add-Content -Path $outPath -Value "        backgroundColor: colors.background,"  
Add-Content -Path $outPath -Value "        backgroundImage: ["  
Add-Content -Path $outPath -Value "          'radial-gradient(ellipse 120%% 50%% at 60%% -8%%, rgba(254,192,15,0.045) 0%%, transparent 55%%)',"  
Add-Content -Path $outPath -Value "          'radial-gradient(' + dot + ' 1px, transparent 1px)',"  
Add-Content -Path $outPath -Value "        ].join(', '),"  
Add-Content -Path $outPath -Value "        backgroundSize: 'auto, 24px 24px',"  
Add-Content -Path $outPath -Value "        fontFamily: `"'Instrument Sans', 'Quicksand', sans-serif`","  
Add-Content -Path $outPath -Value "        color: colors.text,"  
Add-Content -Path $outPath -Value "      }}"  
Add-Content -Path $outPath -Value "    ^>" 
Add-Content -Path $outPath -Value "      ^<div style={{ height: '1px', background: 'linear-gradient(90deg, transparent 0%%, var(--accent) 45%%, rgba(254,192,15,0.25) 65%%, transparent 100%%)', opacity: 0.45 }} /^>"  
Add-Content -Path $outPath -Value "      ^<div style={{ borderBottom: '1px solid ' + colors.border, padding: isMobile ? '24px 20px 0' : '40px 52px 0' }}^>"  
Add-Content -Path $outPath -Value "        ^<div style={{ maxWidth: '1360px', margin: '0 auto' }}^>"  
Add-Content -Path $outPath -Value "          ^<div style={{ display: 'flex', alignItems: isMobile ? 'flex-start' : 'center', justifyContent: 'space-between', gap: '16px', flexDirection: isMobile ? 'column' : 'row', marginBottom: '24px' }}^>"  
Add-Content -Path $outPath -Value "            ^<div^>"  
Add-Content -Path $outPath -Value "              ^<div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(254,192,15,0.08)', border: '1px solid rgba(254,192,15,0.2)', borderRadius: '100px', padding: '4px 14px 4px 10px', marginBottom: '14px' }}^>"  
Add-Content -Path $outPath -Value "                ^<div style={{ width: 5, height: 5, borderRadius: '50%%', background: 'var(--accent)', animation: 'kb-pulse 2.4s ease-in-out infinite' }} /^>"  
Add-Content -Path $outPath -Value "                ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.16em', textTransform: 'uppercase', color: 'var(--accent)' }}^>"  
Add-Content -Path $outPath -Value "                  Knowledge Base {stats ? stats.total_documents + ' docs' : 'Loading'}"  
Add-Content -Path $outPath -Value "                ^</span^>"  
Add-Content -Path $outPath -Value "              ^</div^>" 
Add-Content -Path $outPath -Value "              ^<h1 style={{ fontFamily: `"'Syne', sans-serif`", fontSize: isMobile ? '28px' : '42px', fontWeight: 800, letterSpacing: '-0.025em', lineHeight: 1.08, color: colors.text, margin: 0 }}^>"  
Add-Content -Path $outPath -Value "                Knowledge ^<span style={{ color: 'var(--accent)' }}^>Base^</span^>"  
Add-Content -Path $outPath -Value "              ^</h1^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ fontSize: '13px', color: colors.textMuted, lineHeight: 1.7, margin: '6px 0 0' }}^>Upload, search, and manage your documents^</p^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "              ^<button onClick={loadData} title=`"Refresh`" style={{ width: 38, height: 38, borderRadius: '9px', border: '1px solid ' + colors.border, background: colors.cardBg, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: colors.textMuted, boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                ^<RefreshCw size={14} /^>"  
Add-Content -Path $outPath -Value "              ^</button^>"  
Add-Content -Path $outPath -Value "              ^<button onClick={() =^> setShowFeedback(true)} style={{ height: 38, padding: '0 16px', borderRadius: '9px', border: '1px solid ' + colors.border, background: colors.cardBg, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '7px', color: colors.textMuted, fontFamily: `"'Syne', sans-serif`", fontSize: '11px', fontWeight: 600, letterSpacing: '0.07em', textTransform: 'uppercase', boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                ^<MessageSquarePlus size={13} /^>"  
Add-Content -Path $outPath -Value "                {!isMobile ^&^& 'Feedback'}"  
Add-Content -Path $outPath -Value "              ^</button^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ^</div^>" 
Add-Content -Path $outPath -Value "          {stats ^&^& !loading ^&^& ("  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', marginBottom: '4px' }}^>"  
Add-Content -Path $outPath -Value "              {["  
Add-Content -Path $outPath -Value "                { label: 'Documents', value: stats.total_documents, icon: FileText, color: 'var(--accent)' },"  
Add-Content -Path $outPath -Value "                { label: 'Total Size', value: formatFileSize(stats.total_size), icon: HardDrive, color: '#60A5FA' },"  
Add-Content -Path $outPath -Value "                { label: 'Categories', value: Object.keys(stats.categories).length, icon: FolderOpen, color: '#34D399' },"  
Add-Content -Path $outPath -Value "                { label: 'Bookmarks', value: bookmarkedIds.size, icon: BookOpen, color: '#A78BFA' },"  
Add-Content -Path $outPath -Value "              ].map(({ label, value, icon: Icon, color }) =^> ("  
Add-Content -Path $outPath -Value "                ^<div key={label} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 16px', background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '10px', boxShadow: colors.shadow, position: 'relative', overflow: 'hidden' }}^>"  
Add-Content -Path $outPath -Value "                  ^<div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '1.5px', background: 'linear-gradient(90deg, ' + color + ', transparent)', opacity: 0.55 }} /^>"  
Add-Content -Path $outPath -Value "                  ^<div style={{ width: 30, height: 30, borderRadius: '8px', background: color + '18', display: 'flex', alignItems: 'center', justifyContent: 'center' }}^>"  
Add-Content -Path $outPath -Value "                    ^<Icon size={14} color={color} /^>"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                  ^<div^>"  
Add-Content -Path $outPath -Value "                    ^<div style={{ fontFamily: `"'DM Mono', monospace`", fontSize: isMobile ? '20px' : '24px', fontWeight: 400, color: colors.text, letterSpacing: '-0.02em', lineHeight: 1 }}^>"  
Add-Content -Path $outPath -Value "                      {typeof value === 'number' ? String(value).padStart(2, '0') : value}"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                    ^<div style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '8.5px', letterSpacing: '0.12em', textTransform: 'uppercase', color: colors.textMuted, marginTop: '2px' }}^>{label}^</div^>"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                ^</div^>"  
Add-Content -Path $outPath -Value "              ))}"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          )}" 
Add-Content -Path $outPath -Value "          ^<div style={{ display: 'flex', gap: '2px', marginTop: '20px' }}^>"  
Add-Content -Path $outPath -Value "            {TABS.map(({ id, label, icon: Icon }) =^> {"  
Add-Content -Path $outPath -Value "              const isActive = activeTab === id;"  
Add-Content -Path $outPath -Value "              return ("  
Add-Content -Path $outPath -Value "                ^<button key={id} onClick={() =^> setActiveTab(id)} style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: isMobile ? '10px 14px' : '11px 22px', background: 'transparent', border: 'none', borderBottom: '2px solid ' + (isActive ? 'var(--accent)' : 'transparent'), color: isActive ? 'var(--accent)' : colors.textMuted, fontFamily: `"'Syne', sans-serif`", fontSize: '11px', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', cursor: 'pointer' }}^>"  
Add-Content -Path $outPath -Value "                  ^<Icon size={13} /^>"  
Add-Content -Path $outPath -Value "                  {label}"  
Add-Content -Path $outPath -Value "                ^</button^>"  
Add-Content -Path $outPath -Value "              );"  
Add-Content -Path $outPath -Value "            })}"  
Add-Content -Path $outPath -Value "          ^</div^>"  
Add-Content -Path $outPath -Value "        ^</div^>"  
Add-Content -Path $outPath -Value "      ^</div^>" 
Add-Content -Path $outPath -Value "      ^<div style={{ padding: isMobile ? '20px' : '28px 52px 64px', maxWidth: '1360px', margin: '0 auto' }}^>"  
Add-Content -Path $outPath -Value "        {error ^&^& ("  
Add-Content -Path $outPath -Value "          ^<div style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', borderRadius: '12px', padding: '11px 18px', marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' }}^>"  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}^>"  
Add-Content -Path $outPath -Value "              ^<AlertCircle size={15} color=`"#EF4444`" /^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ color: '#FCA5A5', fontSize: '12.5px', margin: 0 }}^>{error}^</p^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', gap: '6px' }}^>"  
Add-Content -Path $outPath -Value "              ^<button onClick={() =^> { setError(''); loadData(); }} style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', cursor: 'pointer', color: '#FCA5A5', padding: '4px 12px', borderRadius: '6px', fontSize: '11px', fontFamily: `"'DM Mono', monospace`" }}^>Retry^</button^>"  
Add-Content -Path $outPath -Value "              ^<button onClick={() =^> setError('')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: colors.textMuted, fontSize: '16px' }}^>x^</button^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ^</div^>"  
Add-Content -Path $outPath -Value "        )}" 
Add-Content -Path $outPath -Value "        {loading ? ("  
Add-Content -Path $outPath -Value "          ^<div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '100px 0', gap: '16px' }}^>"  
Add-Content -Path $outPath -Value "            ^<div style={{ width: 48, height: 48, borderRadius: '14px', background: 'rgba(254,192,15,0.08)', border: '1px solid rgba(254,192,15,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}^>"  
Add-Content -Path $outPath -Value "              ^<Loader2 size={22} color=`"var(--accent)`" style={{ animation: 'spin 1s linear infinite' }} /^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "            ^<p style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '11px', letterSpacing: '0.1em', textTransform: 'uppercase', color: colors.textMuted }}^>Loading knowledge base...^</p^>"  
Add-Content -Path $outPath -Value "          ^</div^>"  
Add-Content -Path $outPath -Value "        ) : ("  
Add-Content -Path $outPath -Value "          ^<^>" 
Add-Content -Path $outPath -Value "            {activeTab === 'discover' ^&^& ("  
Add-Content -Path $outPath -Value "              ^<div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : isTablet ? '1fr' : '1fr 300px', gap: '20px' }}^>"  
Add-Content -Path $outPath -Value "                ^<div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}^>"  
Add-Content -Path $outPath -Value "                  ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', padding: '20px 22px', boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                    ^<div style={{ position: 'relative' }}^>"  
Add-Content -Path $outPath -Value "                      ^<Search size={16} color={colors.textMuted} style={{ position: 'absolute', left: '14px', top: '50%%', transform: 'translateY(-50%%)' }} /^>"  
Add-Content -Path $outPath -Value "                      ^<input type=`"text`" value={searchQuery} onChange={(e) =^> { setSearchQuery(e.target.value); setActiveTab('documents'); }} placeholder=`"Search documents by name, category...\`" style={{ width: '100%%', height: '44px', paddingLeft: '42px', paddingRight: '16px', backgroundColor: colors.inputBg, border: '1px solid ' + colors.border, borderRadius: '10px', color: colors.text, fontSize: '13.5px', fontFamily: `"'Quicksand', sans-serif`", outline: 'none', boxSizing: 'border-box' }} /^>"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  ^</div^>" 
Add-Content -Path $outPath -Value "                  {recentDocs.length ^> 0 ^&^& ("  
Add-Content -Path $outPath -Value "                    ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', overflow: 'hidden', boxShadow: colors.shadow, position: 'relative' }}^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '1.5px', background: 'linear-gradient(90deg, var(--accent) 0%%, rgba(254,192,15,0.1) 60%%, transparent 100%%)' }} /^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ padding: '16px 22px', borderBottom: '1px solid ' + colors.border, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}^>"  
Add-Content -Path $outPath -Value "                        ^<div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}^>"  
Add-Content -Path $outPath -Value "                          ^<Clock size={13} color=`"var(--accent)`" /^>"  
Add-Content -Path $outPath -Value "                          ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: colors.textMuted }}^>Recently Added^</span^>"  
Add-Content -Path $outPath -Value "                        ^</div^>"  
Add-Content -Path $outPath -Value "                        ^<button onClick={() =^> setActiveTab('documents')} style={{ background: 'none', border: 'none', cursor: 'pointer', fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--accent)', opacity: 0.7 }}^>View All -^>^</button^>"  
Add-Content -Path $outPath -Value "                      ^</div^>" 
Add-Content -Path $outPath -Value "                      {recentDocs.map((doc, idx) =^> {"  
Add-Content -Path $outPath -Value "                        const cc = catColors[doc.category ?? 'general'] ?? catColors.general;"  
Add-Content -Path $outPath -Value "                        const fColor = getFileColor(doc.filename);"  
Add-Content -Path $outPath -Value "                        return ("  
Add-Content -Path $outPath -Value "                          ^<div key={doc.id} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '11px 22px', borderBottom: idx ^< recentDocs.length - 1 ? '1px solid ' + colors.border : 'none', cursor: 'pointer', transition: 'background .15s' }} onClick={() =^> setViewerDoc(doc)} onMouseEnter={(e) =^> (e.currentTarget.style.background = colors.hoverBg)} onMouseLeave={(e) =^> (e.currentTarget.style.background = 'transparent')}^>"  
Add-Content -Path $outPath -Value "                            ^<div style={{ width: 32, height: 32, borderRadius: '9px', background: fColor + '14', border: '1px solid ' + fColor + '30', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "                              ^<FileText size={14} color={fColor} /^>"  
Add-Content -Path $outPath -Value "                            ^</div^>"  
Add-Content -Path $outPath -Value "                            ^<div style={{ flex: 1, minWidth: 0 }}^>"  
Add-Content -Path $outPath -Value "                              ^<p style={{ color: colors.text, fontSize: '13px', fontWeight: 500, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}^>{doc.filename}^</p^>"  
Add-Content -Path $outPath -Value "                              ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9.5px', color: colors.textMuted }}^>{new Date(doc.created_at).toLocaleDateString()}^</span^>"  
Add-Content -Path $outPath -Value "                            ^</div^>"  
Add-Content -Path $outPath -Value "                            ^<div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "                              {doc.category ^&^& ^<span style={{ fontSize: '9px', padding: '2px 8px', borderRadius: '5px', background: cc.bg, color: cc.text, fontFamily: `"'DM Mono', monospace`", letterSpacing: '0.06em', textTransform: 'uppercase' }}^>{doc.category}^</span^>}"  
Add-Content -Path $outPath -Value "                              ^<button onClick={(e) =^> { e.stopPropagation(); handleBookmark(doc.id); }} style={{ background: 'none', border: 'none', cursor: 'pointer', color: bookmarkedIds.has(doc.id) ? 'var(--accent)' : colors.textMuted, padding: 2, display: 'flex', opacity: bookmarkedIds.has(doc.id) ? 1 : 0.45 }}^>"  
Add-Content -Path $outPath -Value "                                {bookmarkedIds.has(doc.id) ? ^<BookmarkCheck size={13} /^> : ^<Bookmark size={13} /^>}"  
Add-Content -Path $outPath -Value "                              ^</button^>"  
Add-Content -Path $outPath -Value "                            ^</div^>"  
Add-Content -Path $outPath -Value "                          ^</div^>"  
Add-Content -Path $outPath -Value "                        );"  
Add-Content -Path $outPath -Value "                      })}"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  )}" 
Add-Content -Path $outPath -Value "                  {bookmarkedDocs.length ^> 0 ^&^& ("  
Add-Content -Path $outPath -Value "                    ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', overflow: 'hidden', boxShadow: colors.shadow, position: 'relative' }}^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '1.5px', background: 'linear-gradient(90deg, #A78BFA 0%%, rgba(167,139,250,0.1) 60%%, transparent 100%%)' }} /^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ padding: '16px 22px', borderBottom: '1px solid ' + colors.border, display: 'flex', alignItems: 'center', gap: '10px' }}^>"  
Add-Content -Path $outPath -Value "                        ^<BookOpen size={13} color=`"#A78BFA`" /^>"  
Add-Content -Path $outPath -Value "                        ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: colors.textMuted }}^>Bookmarked^</span^>"  
Add-Content -Path $outPath -Value "                        ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', padding: '2px 8px', borderRadius: '5px', background: 'rgba(167,139,250,0.12)', color: '#A78BFA' }}^>{bookmarkedDocs.length}^</span^>"  
Add-Content -Path $outPath -Value "                      ^</div^>"  
Add-Content -Path $outPath -Value "                      {bookmarkedDocs.map((doc, idx) =^> ("  
Add-Content -Path $outPath -Value "                        ^<div key={doc.id} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '11px 22px', borderBottom: idx ^< bookmarkedDocs.length - 1 ? '1px solid ' + colors.border : 'none', cursor: 'pointer', transition: 'background .15s' }} onClick={() =^> setViewerDoc(doc)} onMouseEnter={(e) =^> (e.currentTarget.style.background = colors.hoverBg)} onMouseLeave={(e) =^> (e.currentTarget.style.background = 'transparent')}^>"  
Add-Content -Path $outPath -Value "                          ^<FileText size={13} color=`"#A78BFA`" style={{ flexShrink: 0 }} /^>"  
Add-Content -Path $outPath -Value "                          ^<span style={{ color: colors.text, fontSize: '13px', fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1 }}^>{doc.filename}^</span^>"  
Add-Content -Path $outPath -Value "                          ^<button onClick={(e) =^> { e.stopPropagation(); handleBookmark(doc.id); }} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--accent)', padding: 2, display: 'flex', flexShrink: 0 }}^>^<BookmarkCheck size={13} /^>^</button^>"  
Add-Content -Path $outPath -Value "                        ^</div^>"  
Add-Content -Path $outPath -Value "                      ))}"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  )}"  
Add-Content -Path $outPath -Value "                ^</div^>" 
Add-Content -Path $outPath -Value "                ^<div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}^>"  
Add-Content -Path $outPath -Value "                  {stats ^&^& ("  
Add-Content -Path $outPath -Value "                    ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', overflow: 'hidden', boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ padding: '14px 18px', borderBottom: '1px solid ' + colors.border, display: 'flex', alignItems: 'center', gap: '8px' }}^>"  
Add-Content -Path $outPath -Value "                        ^<TrendingUp size={13} color=`"var(--accent)`" /^>"  
Add-Content -Path $outPath -Value "                        ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: colors.textMuted }}^>Categories^</span^>"  
Add-Content -Path $outPath -Value "                      ^</div^>"  
Add-Content -Path $outPath -Value "                      ^<div style={{ padding: '10px 14px', display: 'flex', flexDirection: 'column', gap: '3px' }}^>"  
Add-Content -Path $outPath -Value "                        {categories.map((cat) =^> {"  
Add-Content -Path $outPath -Value "                          const count = cat === 'all' ? stats.total_documents : (stats.categories[cat] ?? 0);"  
Add-Content -Path $outPath -Value "                          const isActive = activeCategory === cat;"  
Add-Content -Path $outPath -Value "                          const cc = catColors[cat] ?? catColors.general;"  
Add-Content -Path $outPath -Value "                          return ("  
Add-Content -Path $outPath -Value "                            ^<button key={cat} onClick={() =^> { setActiveCategory(cat); setActiveTab('documents'); }} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '7px 10px', borderRadius: '8px', border: '1px solid ' + (isActive ? (cat === 'all' ? 'var(--accent)' : cc.text) : 'transparent'), backgroundColor: isActive ? (cat === 'all' ? 'rgba(254,192,15,0.08)' : cc.bg) : 'transparent', cursor: 'pointer', width: '100%%', textAlign: 'left' }}^>"  
Add-Content -Path $outPath -Value "                              ^<span style={{ fontSize: '12px', fontWeight: 600, color: isActive ? (cat === 'all' ? 'var(--accent)' : cc.text) : colors.text, fontFamily: `"'Syne', sans-serif`", textTransform: 'uppercase', letterSpacing: '0.05em' }}^>{cat === 'all' ? 'All' : cat}^</span^>"  
Add-Content -Path $outPath -Value "                              ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '11px', color: isActive ? (cat === 'all' ? 'var(--accent)' : cc.text) : colors.textMuted }}^>{count}^</span^>"  
Add-Content -Path $outPath -Value "                            ^</button^>"  
Add-Content -Path $outPath -Value "                          );"  
Add-Content -Path $outPath -Value "                        })}"  
Add-Content -Path $outPath -Value "                      ^</div^>"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  )}" 
Add-Content -Path $outPath -Value "                  ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', overflow: 'hidden', boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                    ^<div style={{ padding: '14px 18px', borderBottom: '1px solid ' + colors.border, display: 'flex', alignItems: 'center', gap: '8px' }}^>"  
Add-Content -Path $outPath -Value "                      ^<Upload size={13} color=`"var(--accent)`" /^>"  
Add-Content -Path $outPath -Value "                      ^<span style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '9px', letterSpacing: '0.18em', textTransform: 'uppercase', color: colors.textMuted }}^>Quick Upload^</span^>"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                    ^<div style={{ padding: '16px 18px' }}^>"  
Add-Content -Path $outPath -Value "                      ^<button onClick={() =^> { setActiveTab('upload'); fileInputRef.current?.click(); }} style={{ width: '100%%', padding: '12px', borderRadius: '10px', border: '2px dashed rgba(254,192,15,0.3)', background: 'rgba(254,192,15,0.04)', color: 'var(--accent)', cursor: 'pointer', fontFamily: `"'Syne', sans-serif`", fontSize: '12px', fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}^>"  
Add-Content -Path $outPath -Value "                        ^<Upload size={14} /^> Choose Files"  
Add-Content -Path $outPath -Value "                      ^</button^>"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                ^</div^>"  
Add-Content -Path $outPath -Value "              ^</div^>"  
Add-Content -Path $outPath -Value "            )}" 
Add-Content -Path $outPath -Value "            {activeTab === 'documents' ^&^& ("  
Add-Content -Path $outPath -Value "              ^<div^>"  
Add-Content -Path $outPath -Value "                ^<div style={{ display: 'flex', gap: '10px', marginBottom: '16px', flexWrap: 'wrap' }}^>"  
Add-Content -Path $outPath -Value "                  ^<div style={{ position: 'relative', flex: 1, minWidth: '200px' }}^>"  
Add-Content -Path $outPath -Value "                    ^<Search size={14} color={colors.textMuted} style={{ position: 'absolute', left: '12px', top: '50%%', transform: 'translateY(-50%%)' }} /^>"  
Add-Content -Path $outPath -Value "                    ^<input type=`"text`" value={searchQuery} onChange={(e) =^> setSearchQuery(e.target.value)} placeholder=`"Filter documents...\`" style={{ width: '100%%', height: '38px', paddingLeft: '34px', paddingRight: '12px', backgroundColor: colors.inputBg, border: '1px solid ' + colors.border, borderRadius: '9px', color: colors.text, fontSize: '13px', fontFamily: `"'Quicksand', sans-serif`", outline: 'none', boxSizing: 'border-box' }} /^>"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                  ^<div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}^>"  
Add-Content -Path $outPath -Value "                    {categories.map((cat) =^> ("  
Add-Content -Path $outPath -Value "                      ^<button key={cat} onClick={() =^> setActiveCategory(cat)} style={{ padding: '5px 14px', borderRadius: '100px', border: '1px solid ' + (activeCategory === cat ? 'var(--accent)' : colors.border), background: activeCategory === cat ? 'rgba(254,192,15,0.1)' : 'transparent', color: activeCategory === cat ? 'var(--accent)' : colors.textMuted, fontFamily: `"'DM Mono', monospace`", fontSize: '9.5px', letterSpacing: '0.1em', textTransform: 'uppercase', cursor: 'pointer' }}^>"  
Add-Content -Path $outPath -Value "                        {cat === 'all' ? 'All' : cat}"  
Add-Content -Path $outPath -Value "                      ^</button^>"  
Add-Content -Path $outPath -Value "                    ))}"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                ^</div^>" 
Add-Content -Path $outPath -Value "                ^<div style={{ background: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', overflow: 'hidden', boxShadow: colors.shadow }}^>"  
Add-Content -Path $outPath -Value "                  {filteredDocs.length === 0 ? ("  
Add-Content -Path $outPath -Value "                    ^<div style={{ padding: '60px', textAlign: 'center' }}^>"  
Add-Content -Path $outPath -Value "                      ^<FolderOpen size={40} color={colors.textMuted} style={{ opacity: 0.3, marginBottom: '12px' }} /^>"  
Add-Content -Path $outPath -Value "                      ^<p style={{ color: colors.textMuted, fontSize: '14px', margin: 0 }}^>"  
Add-Content -Path $outPath -Value "                        {searchQuery ? 'No documents matching ' + searchQuery : 'No documents yet'}"  
Add-Content -Path $outPath -Value "                      ^</p^>"  
Add-Content -Path $outPath -Value "                    ^</div^>"  
Add-Content -Path $outPath -Value "                  ) : ("  
Add-Content -Path $outPath -Value "                    filteredDocs.map((doc, idx) =^> {"  
Add-Content -Path $outPath -Value "                      const fColor = getFileColor(doc.filename);"  
Add-Content -Path $outPath -Value "                      const cc = catColors[doc.category ?? 'general'] ?? catColors.general;"  
Add-Content -Path $outPath -Value "                      return ("  
Add-Content -Path $outPath -Value "                        ^<div key={doc.id} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 22px', borderBottom: idx ^< filteredDocs.length - 1 ? '1px solid ' + colors.border : 'none', transition: 'background .15s' }} onMouseEnter={(e) =^> (e.currentTarget.style.background = colors.hoverBg)} onMouseLeave={(e) =^> (e.currentTarget.style.background = 'transparent')}^>"  
Add-Content -Path $outPath -Value "                          ^<div style={{ width: 38, height: 38, borderRadius: '9px', background: fColor + '14', border: '1px solid ' + fColor + '30', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, cursor: 'pointer' }} onClick={() =^> setViewerDoc(doc)}^>"  
Add-Content -Path $outPath -Value "                            ^<FileText size={16} color={fColor} /^>"  
Add-Content -Path $outPath -Value "                          ^</div^>" 
Add-Content -Path $outPath -Value "                          ^<div style={{ flex: 1, minWidth: 0, cursor: 'pointer' }} onClick={() =^> setViewerDoc(doc)}^>"  
Add-Content -Path $outPath -Value "                            ^<p style={{ color: colors.text, fontSize: '13px', fontWeight: 600, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}^>{doc.filename}^</p^>"  
Add-Content -Path $outPath -Value "                            ^<div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginTop: '3px', flexWrap: 'wrap' }}^>"  
Add-Content -Path $outPath -Value "                              {doc.category ^&^& ^<span style={{ fontSize: '9px', padding: '2px 7px', borderRadius: '4px', background: cc.bg, color: cc.text, fontFamily: `"'DM Mono', monospace`", letterSpacing: '0.06em', textTransform: 'uppercase' }}^>{doc.category}^</span^>}"  
Add-Content -Path $outPath -Value "                              ^<span style={{ color: colors.textMuted, fontSize: '11px' }}^>{formatFileSize(doc.file_size ?? doc.size)}^</span^>"  
Add-Content -Path $outPath -Value "                              {doc.chunk_count != null ^&^& ^<span style={{ color: colors.textMuted, fontSize: '11px', fontFamily: `"'DM Mono', monospace`" }}^>{doc.chunk_count} chunks^</span^>}"  
Add-Content -Path $outPath -Value "                              ^<span style={{ color: colors.textMuted, fontSize: '11px' }}^>{new Date(doc.created_at).toLocaleDateString()}^</span^>"  
Add-Content -Path $outPath -Value "                            ^</div^>"  
Add-Content -Path $outPath -Value "                          ^</div^>"  
Add-Content -Path $outPath -Value "                          ^<div style={{ display: 'flex', gap: '4px', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "                            ^<button onClick={() =^> handleBookmark(doc.id)} style={{ width: '32px', height: '32px', borderRadius: '7px', border: '1px solid ' + (bookmarkedIds.has(doc.id) ? 'var(--accent)' : colors.border), background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: bookmarkedIds.has(doc.id) ? 'var(--accent)' : colors.textMuted }}^>"  
Add-Content -Path $outPath -Value "                              {bookmarkedIds.has(doc.id) ? ^<BookmarkCheck size={13} /^> : ^<Bookmark size={13} /^>}"  
Add-Content -Path $outPath -Value "                            ^</button^>"  
Add-Content -Path $outPath -Value "                            ^<button onClick={() =^> setViewerDoc(doc)} style={{ width: '32px', height: '32px', borderRadius: '7px', border: '1px solid ' + colors.border, background: 'transparent', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: colors.textMuted }} title=`"View document`"^>^<Search size={13} /^>^</button^>"  
Add-Content -Path $outPath -Value "                            ^<button onClick={() =^> handleDelete(doc.id)} style={{ width: '32px', height: '32px', borderRadius: '7px', border: '1px solid rgba(239,68,68,0.3)', background: 'rgba(239,68,68,0.06)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#ef4444' }} title=`"Delete document`"^>^<X size={13} /^>^</button^>"  
Add-Content -Path $outPath -Value "                          ^</div^>"  
Add-Content -Path $outPath -Value "                        ^</div^>"  
Add-Content -Path $outPath -Value "                      );"  
Add-Content -Path $outPath -Value "                    })"  
Add-Content -Path $outPath -Value "                  )}"  
Add-Content -Path $outPath -Value "                ^</div^>"  
Add-Content -Path $outPath -Value "              ^</div^>"  
Add-Content -Path $outPath -Value "            )}" 
