$outPath = 'c:\Users\SohaibAli\Videos\Development\AnalystDevelopmentFrontend\src\components\knowledge\KBFileViewerModal.tsx'  
Set-Content -Path $outPath -Value "'use client';" -Encoding UTF8  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "import React, { useCallback, useEffect, useRef, useState } from 'react';"  
Add-Content -Path $outPath -Value "import { X, Download, FileText, FileCode, FileSpreadsheet, File, Loader2, AlertCircle, Copy, CheckCircle, ExternalLink } from 'lucide-react';"  
Add-Content -Path $outPath -Value "import kbApi from '@/lib/kbApi';"  
Add-Content -Path $outPath -Value "import { parseFileForPreview } from '@/lib/filePreview';"  
Add-Content -Path $outPath -Value "import type { KBDocument } from '@/types/kb';"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function getExt(filename: string): string { return filename.split('.').pop()?.toLowerCase() ^|^| ''; }"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function getFileIcon(filename: string) {"  
Add-Content -Path $outPath -Value "  const ext = getExt(filename);"  
Add-Content -Path $outPath -Value "  switch (ext) {"  
Add-Content -Path $outPath -Value "    case 'pdf': return { Icon: FileText, color: '#ef4444' };"  
Add-Content -Path $outPath -Value "    case 'doc': case 'docx': return { Icon: FileText, color: '#3b82f6' };"  
Add-Content -Path $outPath -Value "    case 'txt': case 'md': return { Icon: FileCode, color: '#22c55e' };"  
Add-Content -Path $outPath -Value "    case 'csv': case 'xlsx': case 'xls': return { Icon: FileSpreadsheet, color: '#22c55e' };"  
Add-Content -Path $outPath -Value "    case 'json': case 'xml': case 'html': case 'htm': return { Icon: FileCode, color: '#f59e0b' };"  
Add-Content -Path $outPath -Value "    default: return { Icon: File, color: '#9ca3af' };"  
Add-Content -Path $outPath -Value "  }"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "function formatSize(bytes: number ^| null ^| undefined): string {"  
Add-Content -Path $outPath -Value "  const n = Number(bytes ?? 0);"  
Add-Content -Path $outPath -Value "  if (n ^< 1024) return n + ' B';"  
Add-Content -Path $outPath -Value "  if (n ^< 1024 * 1024) return (n / 1024).toFixed(1) + ' KB';"  
Add-Content -Path $outPath -Value "  return (n / (1024 * 1024)).toFixed(2) + ' MB';"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "const TEXT_EXTS = ['txt', 'md', 'json', 'xml', 'html', 'htm', 'csv'];"  
Add-Content -Path $outPath -Value "const PARSEABLE_EXTS = ['pdf', 'docx', 'doc', 'xlsx', 'xls', 'csv', 'txt', 'md', 'json', 'html', 'htm', 'xml'];"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "export interface KBFileViewerModalProps {"  
Add-Content -Path $outPath -Value "  doc: KBDocument;"  
Add-Content -Path $outPath -Value "  onClose: () =^> void;"  
Add-Content -Path $outPath -Value "  isDark: boolean;"  
Add-Content -Path $outPath -Value "  colors: Record^<string, string^>;"  
Add-Content -Path $outPath -Value "  chunkPreview?: string;"  
Add-Content -Path $outPath -Value "}" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "export default function KBFileViewerModal({ doc, onClose, isDark, colors, chunkPreview }: KBFileViewerModalProps) {"  
Add-Content -Path $outPath -Value "  const [loading, setLoading] = useState(true);"  
Add-Content -Path $outPath -Value "  const [error, setError] = useState^<string ^| null^>(null);"  
Add-Content -Path $outPath -Value "  const [contentType, setContentType] = useState^<'html' ^| 'text' ^| 'table' ^| 'json' ^| 'unsupported'^>('text');"  
Add-Content -Path $outPath -Value "  const [content, setContent] = useState^<string ^| null^>(null);"  
Add-Content -Path $outPath -Value "  const [tables, setTables] = useState^<{ headers: string[]; rows: string[][]; name?: string }[] ^| undefined^>(undefined);"  
Add-Content -Path $outPath -Value "  const [copied, setCopied] = useState(false);"  
Add-Content -Path $outPath -Value "  const [showRawFallback, setShowRawFallback] = useState(false);"  
Add-Content -Path $outPath -Value "  const contentRef = useRef^<HTMLDivElement^>(null);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const ext = getExt(doc.filename);"  
Add-Content -Path $outPath -Value "  const { Icon: FIcon, color: fColor } = getFileIcon(doc.filename);"  
Add-Content -Path $outPath -Value "  const downloadUrl = kbApi.getDownloadUrl(doc.id);"  
Add-Content -Path $outPath -Value "  const attachmentUrl = kbApi.getAttachmentUrl(doc.id);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const loadContent = useCallback(async () =^> {"  
Add-Content -Path $outPath -Value "    setLoading(true); setError(null); setContent(null); setTables(undefined);"  
Add-Content -Path $outPath -Value "    try {"  
Add-Content -Path $outPath -Value "      if (PARSEABLE_EXTS.includes(ext)) {"  
Add-Content -Path $outPath -Value "        const blob = await kbApi.fetchBlob(doc.id);"  
Add-Content -Path $outPath -Value "        if (blob.size ^> 0) {"  
Add-Content -Path $outPath -Value "          const parsed = await parseFileForPreview(blob, doc.filename);"  
Add-Content -Path $outPath -Value "          if (parsed.type !== 'unsupported') {"  
Add-Content -Path $outPath -Value "            setContentType(parsed.type as any); setContent(parsed.content); setTables(parsed.tables);"  
Add-Content -Path $outPath -Value "            setLoading(false); return;"  
Add-Content -Path $outPath -Value "          }"  
Add-Content -Path $outPath -Value "        }"  
Add-Content -Path $outPath -Value "      }" 
Add-Content -Path $outPath -Value "      try {"  
Add-Content -Path $outPath -Value "        const raw = await kbApi.getRawDocument(doc.id);"  
Add-Content -Path $outPath -Value "        if (raw.raw_content) {"  
Add-Content -Path $outPath -Value "          setContentType('text'); setContent(raw.raw_content); setShowRawFallback(true);"  
Add-Content -Path $outPath -Value "          setLoading(false); return;"  
Add-Content -Path $outPath -Value "        }"  
Add-Content -Path $outPath -Value "      } catch { /* ignore */ }"  
Add-Content -Path $outPath -Value "      setContentType('unsupported'); setContent(null);"  
Add-Content -Path $outPath -Value "    } catch (err) {"  
Add-Content -Path $outPath -Value "      setError(err instanceof Error ? err.message : 'Failed to load document');"  
Add-Content -Path $outPath -Value "    } finally { setLoading(false); }"  
Add-Content -Path $outPath -Value "  }, [doc.id, doc.filename, ext]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  useEffect(() =^> { loadContent(); }, [loadContent]);"  
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  useEffect(() =^> {"  
Add-Content -Path $outPath -Value "    if (!chunkPreview ^|^| !content ^|^| !contentRef.current) return;"  
Add-Content -Path $outPath -Value "    const needle = chunkPreview.slice(0, 80).toLowerCase();"  
Add-Content -Path $outPath -Value "    const text = contentRef.current.innerText?.toLowerCase() ?? '';"  
Add-Content -Path $outPath -Value "    const idx = text.indexOf(needle);"  
Add-Content -Path $outPath -Value "    if (idx ^> -1) {"  
Add-Content -Path $outPath -Value "      const ratio = idx / text.length;"  
Add-Content -Path $outPath -Value "      const el = contentRef.current;"  
Add-Content -Path $outPath -Value "      el.scrollTop = ratio * el.scrollHeight;"  
Add-Content -Path $outPath -Value "    }"  
Add-Content -Path $outPath -Value "  }, [chunkPreview, content]);" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  const handleCopy = () =^> {"  
Add-Content -Path $outPath -Value "    if (content) { navigator.clipboard.writeText(content); setCopied(true); setTimeout(() =^> setCopied(false), 2000); }"  
Add-Content -Path $outPath -Value "  };" 
Add-Content -Path $outPath -Value ""  
Add-Content -Path $outPath -Value "  return ("  
Add-Content -Path $outPath -Value "    ^<div style={{ position: 'fixed', inset: 0, zIndex: 300, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}^>"  
Add-Content -Path $outPath -Value "      ^<div onClick={onClose} style={{ position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.65)', backdropFilter: 'blur(4px)' }} /^>" 
Add-Content -Path $outPath -Value "      ^<div style={{ position: 'relative', width: '100%%', maxWidth: '960px', maxHeight: '90vh', backgroundColor: colors.cardBg, border: '1px solid ' + colors.border, borderRadius: '16px', display: 'flex', flexDirection: 'column', overflow: 'hidden', boxShadow: '0 24px 64px rgba(0,0,0,0.4)' }}^>" 
Add-Content -Path $outPath -Value "        ^<div style={{ padding: '18px 22px', borderBottom: '1px solid ' + colors.border, display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '14px', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "          ^<div style={{ display: 'flex', alignItems: 'flex-start', gap: '14px', flex: 1, minWidth: 0 }}^>"  
Add-Content -Path $outPath -Value "            ^<div style={{ width: 46, height: 46, borderRadius: '11px', backgroundColor: fColor + '14', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, position: 'relative' }}^>"  
Add-Content -Path $outPath -Value "              ^<FIcon size={22} color={fColor} /^>"  
Add-Content -Path $outPath -Value "              ^<span style={{ position: 'absolute', bottom: '-3px', right: '-6px', fontSize: '7px', padding: '1px 4px', borderRadius: '3px', backgroundColor: fColor, color: '#fff', fontWeight: 700, fontFamily: `"'DM Mono', monospace`", lineHeight: '13px', textTransform: 'uppercase' }}^>{ext.toUpperCase() ^|^| 'FILE'}^</span^>"  
Add-Content -Path $outPath -Value "            ^</div^>" 
Add-Content -Path $outPath -Value "            ^<div style={{ flex: 1, minWidth: 0 }}^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ fontFamily: `"'Syne', sans-serif`", fontSize: '16px', fontWeight: 700, color: colors.text, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', letterSpacing: '-0.01em' }}^>{doc.title ^|^| doc.filename}^</p^>"  
Add-Content -Path $outPath -Value "              ^<div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '6px', flexWrap: 'wrap' }}^>"  
Add-Content -Path $outPath -Value "                {doc.category ^&^& ^<span style={{ fontSize: '10px', padding: '2px 8px', borderRadius: '4px', backgroundColor: 'rgba(254,192,15,0.1)', color: 'var(--accent)', fontFamily: `"'DM Mono', monospace`", letterSpacing: '0.06em', textTransform: 'uppercase' }}^>{doc.category}^</span^>}"  
Add-Content -Path $outPath -Value "                ^<span style={{ color: colors.textMuted, fontSize: '11px' }}^>{formatSize(doc.file_size ?? doc.size)}^</span^>"  
Add-Content -Path $outPath -Value "                {showRawFallback ^&^& ^<span style={{ fontSize: '10px', padding: '2px 8px', borderRadius: '4px', backgroundColor: 'rgba(251,146,60,0.1)', color: '#fb923c', fontFamily: `"'DM Mono', monospace`", letterSpacing: '0.06em' }}^>Extracted text^</span^>}"  
Add-Content -Path $outPath -Value "              ^</div^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ^</div^>" 
Add-Content -Path $outPath -Value "          ^<div style={{ display: 'flex', gap: '6px', flexShrink: 0 }}^>"  
Add-Content -Path $outPath -Value "            ^<a href={downloadUrl} target=`"_blank`" rel=`"noopener noreferrer`" style={{ height: '34px', padding: '0 12px', borderRadius: '8px', border: '1px solid rgba(254,192,15,0.3)', backgroundColor: 'rgba(254,192,15,0.08)', color: 'var(--accent)', fontSize: '11px', fontWeight: 600, fontFamily: `"'Syne', sans-serif`", letterSpacing: '0.06em', textTransform: 'uppercase', display: 'inline-flex', alignItems: 'center', gap: '5px', textDecoration: 'none', cursor: 'pointer' }} title=`"Open original file`"^>^<ExternalLink size={12} /^>Open^</a^>"  
Add-Content -Path $outPath -Value "            ^<a href={attachmentUrl} download={doc.filename} style={{ height: '34px', width: '34px', borderRadius: '8px', border: '1px solid ' + colors.border, backgroundColor: 'transparent', color: colors.textMuted, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', textDecoration: 'none', cursor: 'pointer' }} title=`"Download file`"^>^<Download size={14} /^>^</a^>"  
Add-Content -Path $outPath -Value "            {content ^&^& ^<button onClick={handleCopy} style={{ height: '34px', width: '34px', borderRadius: '8px', border: '1px solid ' + colors.border, backgroundColor: 'transparent', color: copied ? '#22c55e' : colors.textMuted, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }} title={copied ? 'Copied!' : 'Copy text'}^>{copied ? ^<CheckCircle size={14} /^> : ^<Copy size={14} /^>}^</button^>}"  
Add-Content -Path $outPath -Value "            ^<button onClick={onClose} style={{ height: '34px', width: '34px', borderRadius: '8px', border: '1px solid ' + colors.border, backgroundColor: 'transparent', color: colors.textMuted, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}^>^<X size={16} /^>^</button^>"  
Add-Content -Path $outPath -Value "          ^</div^>"  
Add-Content -Path $outPath -Value "        ^</div^>" 
Add-Content -Path $outPath -Value "        ^<div ref={contentRef} style={{ flex: 1, overflow: 'auto', padding: '24px' }}^>"  
Add-Content -Path $outPath -Value "          {loading ? ("  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '80px 0', gap: '14px' }}^>"  
Add-Content -Path $outPath -Value "              ^<Loader2 size={28} color=`"var(--accent)`" style={{ animation: 'spin 1s linear infinite' }} /^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ color: colors.textMuted, fontSize: '13px', margin: 0 }}^>Loading document...^</p^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ) : error ? ("  
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '80px 0', gap: '12px' }}^>"  
Add-Content -Path $outPath -Value "              ^<AlertCircle size={32} color=`"#ef4444`" style={{ opacity: 0.7 }} /^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ color: '#ef4444', fontSize: '13px', margin: 0 }}^>{error}^</p^>"  
Add-Content -Path $outPath -Value "              ^<a href={downloadUrl} target=`"_blank`" rel=`"noopener noreferrer`" style={{ color: 'var(--accent)', fontSize: '12px' }}^>Open original file^</a^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ) : contentType === 'unsupported' ^|^| !content ? (" 
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '80px 0', gap: '14px' }}^>"  
Add-Content -Path $outPath -Value "              ^<div style={{ width: 64, height: 64, borderRadius: '16px', backgroundColor: fColor + '14', display: 'flex', alignItems: 'center', justifyContent: 'center' }}^>^<FIcon size={28} color={fColor} /^>^</div^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ color: colors.text, fontSize: '15px', fontWeight: 600, margin: 0, fontFamily: `"'Syne', sans-serif`" }}^>{doc.filename}^</p^>"  
Add-Content -Path $outPath -Value "              ^<p style={{ color: colors.textMuted, fontSize: '13px', margin: 0, textAlign: 'center', maxWidth: 380 }}^>This file type cannot be previewed in the browser. Open or download the original file.^</p^>"  
Add-Content -Path $outPath -Value "              ^<div style={{ display: 'flex', gap: '10px', marginTop: '8px' }}^>"  
Add-Content -Path $outPath -Value "                ^<a href={downloadUrl} target=`"_blank`" rel=`"noopener noreferrer`" style={{ padding: '8px 18px', borderRadius: '9px', border: '1px solid rgba(254,192,15,0.4)', backgroundColor: 'rgba(254,192,15,0.1)', color: 'var(--accent)', fontSize: '12px', fontWeight: 600, fontFamily: `"'Syne', sans-serif`", textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '6px' }}^>^<ExternalLink size={13} /^> Open Original^</a^>"  
Add-Content -Path $outPath -Value "                ^<a href={attachmentUrl} download={doc.filename} style={{ padding: '8px 18px', borderRadius: '9px', border: '1px solid ' + colors.border, backgroundColor: 'transparent', color: colors.textMuted, fontSize: '12px', fontWeight: 600, fontFamily: `"'Syne', sans-serif`", textDecoration: 'none', display: 'inline-flex', alignItems: 'center', gap: '6px' }}^>^<Download size={13} /^> Download^</a^>"  
Add-Content -Path $outPath -Value "              ^</div^>"  
Add-Content -Path $outPath -Value "            ^</div^>"  
Add-Content -Path $outPath -Value "          ) : contentType === 'html' ? (" 
Add-Content -Path $outPath -Value "            ^<div style={{ fontFamily: `"'Quicksand', sans-serif`", fontSize: '13px', lineHeight: 1.7, color: colors.text, backgroundColor: isDark ? '#161616' : '#FAFAFA', borderRadius: '10px', padding: '20px', border: '1px solid ' + colors.border, overflow: 'auto' }} dangerouslySetInnerHTML={{ __html: content }} /^>"  
Add-Content -Path $outPath -Value "          ) : contentType === 'json' ? ("  
Add-Content -Path $outPath -Value "            ^<pre style={{ fontFamily: `"'DM Mono', monospace`", fontSize: '12.5px', lineHeight: 1.7, color: '#22c55e', whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, backgroundColor: isDark ? '#0a0a0a' : '#FAFAFA', borderRadius: '10px', padding: '20px', border: '1px solid ' + colors.border }}^>{content}^</pre^>"  
Add-Content -Path $outPath -Value "          ) : contentType === 'table' ^&^& tables ^&^& tables.length ^> 0 ? (" 
Add-Content -Path $outPath -Value "            ^<div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}^>"  
Add-Content -Path $outPath -Value "              {tables.map((table, tIdx) =^> ("  
Add-Content -Path $outPath -Value "                ^<div key={tIdx}^>"  
Add-Content -Path $outPath -Value "                  {table.name ^&^& ^<p style={{ fontSize: '11px', fontWeight: 700, color: 'var(--accent)', fontFamily: `"'DM Mono', monospace`", letterSpacing: '0.08em', marginBottom: '8px', textTransform: 'uppercase' }}^>Sheet: {table.name}^</p^>}"  
Add-Content -Path $outPath -Value "                  ^<div style={{ overflow: 'auto', borderRadius: '10px', border: '1px solid ' + colors.border, backgroundColor: isDark ? '#161616' : '#FAFAFA' }}^>"  
Add-Content -Path $outPath -Value "                    ^<table style={{ width: '100%%', borderCollapse: 'collapse', fontSize: '12px' }}^>"  
Add-Content -Path $outPath -Value "                      ^<thead^>^<tr^>{table.headers.map((h, hIdx) =^> ^<th key={hIdx} style={{ padding: '9px 13px', textAlign: 'left', fontWeight: 700, color: colors.text, borderBottom: '1px solid ' + colors.border, backgroundColor: isDark ? '#1a1a1a' : '#F5F5F5', whiteSpace: 'nowrap', position: 'sticky', top: 0, zIndex: 1, fontFamily: `"'DM Mono', monospace`", fontSize: '11px' }}^>{h}^</th^>)}^</tr^>^</thead^>"  
Add-Content -Path $outPath -Value "                      ^<tbody^>{table.rows.slice(0, 200).map((row, rIdx) =^> ^<tr key={rIdx} style={{ borderBottom: '1px solid ' + colors.border }} onMouseEnter={(e) =^> { e.currentTarget.style.backgroundColor = isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)'; }} onMouseLeave={(e) =^> { e.currentTarget.style.backgroundColor = 'transparent'; }}^>{row.map((cell, cIdx) =^> ^<td key={cIdx} style={{ padding: '7px 13px', color: colors.text, whiteSpace: 'nowrap', fontSize: '12px' }}^>{cell}^</td^>)}^</tr^>)}^</tbody^>"  
Add-Content -Path $outPath -Value "                    ^</table^>"  
Add-Content -Path $outPath -Value "                    {table.rows.length ^> 200 ^&^& ^<p style={{ padding: '9px 13px', fontSize: '11px', color: colors.textMuted, textAlign: 'center', borderTop: '1px solid ' + colors.border, margin: 0, fontFamily: `"'DM Mono', monospace`" }}^>Showing first 200 of {table.rows.length} rows^</p^>}"  
Add-Content -Path $outPath -Value "                  ^</div^>"  
Add-Content -Path $outPath -Value "                ^</div^>"  
Add-Content -Path $outPath -Value "              ))}"  
Add-Content -Path $outPath -Value "            ^</div^>" 
Add-Content -Path $outPath -Value "          ) : ("  
Add-Content -Path $outPath -Value "            ^<pre style={{ fontFamily: `"'Quicksand', 'Consolas', monospace`", fontSize: '13px', lineHeight: 1.75, color: colors.text, whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, backgroundColor: isDark ? '#161616' : '#FAFAFA', borderRadius: '10px', padding: '20px', border: '1px solid ' + colors.border }}^>{content}^</pre^>"  
Add-Content -Path $outPath -Value "          )}"  
Add-Content -Path $outPath -Value "        ^</div^>"  
Add-Content -Path $outPath -Value "      ^</div^>"  
Add-Content -Path $outPath -Value "      ^<style^>{'@keyframes spin { to { transform: rotate(360deg); } }'}^</style^>"  
Add-Content -Path $outPath -Value "    ^</div^>"  
Add-Content -Path $outPath -Value "  );"  
Add-Content -Path $outPath -Value "}"  
Write-Host 'File 1 written successfully' 
